services:
  n8n:
    build: .
    labels:
      - "caddy_0.handle_path.0_reverse_proxy={{upstreams 5678}}"
    environment:
      - "GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Europe/Berlin}"
      - "TZ=${TZ:-Europe/Berlin}"
      - "NODE_FUNCTION_ALLOW_EXTERNAL=*"
    volumes:
      - "n8n-data:/home/node/.n8n"
    healthcheck:
      test:
        - CMD-SHELL
        - "wget -qO- http://127.0.0.1:5678/"
      interval: 5s
      timeout: 20s
      retries: 10
